import type { EntityDefinition } from '@/shared/grid/configurable/configuration.types';

/**
 * Base Finance definition. It intentionally differs from Loan in row identity, fields, status
 * vocabulary and backend adapter while exercising the same configurable SSRM compiler/runtime.
 */
export const financeEntityDefinition: EntityDefinition = {
  labelKey: 'review.entities.finance',
  dataAdapterKey: 'review-finance',
  rowId: { path: 'recordKey' },
  gridOptions: {
    paginationPageSize: 20,
    cacheBlockSize: 40,
    maxBlocksInCache: 5,
    defaultColDef: {
      resizable: true,
    },
    rowSelection: {
      mode: 'multiRow',
      checkboxes: true,
      headerCheckbox: true,
      selectAll: 'all',
    },
  },
  fields: [
    {
      colId: 'facility',
      field: 'facility',
      labelKey: 'review.finance.facility',
      cellDataType: 'text',
      minWidth: 180,
      sortable: true,
      filter: 'agTextColumnFilter',
      filterParams: {
        filterOptions: ['contains', 'equals', 'notEqual', 'startsWith', 'endsWith'],
      },
      editable: false,
    },
    {
      colId: 'counterparty',
      field: 'counterparty',
      labelKey: 'review.finance.counterparty',
      cellDataType: 'text',
      minWidth: 190,
      sortable: true,
      filter: 'agTextColumnFilter',
      filterParams: {
        filterOptions: ['contains', 'equals', 'notEqual', 'startsWith', 'endsWith'],
      },
      editable: true,
      cellEditor: 'agTextCellEditor',
      cellEditorParams: { maxLength: 120 },
      valueParserKey: 'trimText',
      validationRules: [
        { key: 'required', message: 'Counterparty is required.' },
        {
          key: 'maxLength',
          params: { max: 120 },
          message: 'Counterparty must be 120 characters or fewer.',
        },
      ],
    },
    {
      colId: 'exposure',
      field: 'exposure',
      labelKey: 'review.finance.exposure',
      cellDataType: 'number',
      type: 'numericColumn',
      minWidth: 155,
      sortable: true,
      filter: 'agNumberColumnFilter',
      filterParams: {
        filterOptions: [
          'equals',
          'notEqual',
          'greaterThan',
          'greaterThanOrEqual',
          'lessThan',
          'lessThanOrEqual',
        ],
      },
      editable: true,
      cellEditor: 'agNumberCellEditor',
      cellEditorParams: { min: 0, max: 100_000_000 },
      valueFormatterKey: 'rowCurrency',
      validationRules: [
        {
          key: 'numberRange',
          params: { min: 0, max: 100_000_000 },
          message: 'Exposure must be between 0 and 100,000,000.',
        },
      ],
    },
    {
      colId: 'currency',
      field: 'currency',
      labelKey: 'review.finance.currency',
      cellDataType: 'text',
      maxWidth: 120,
      sortable: true,
      filter: 'agTextColumnFilter',
      filterParams: { filterOptions: ['equals', 'notEqual'] },
      editable: false,
    },
    {
      colId: 'desk',
      field: 'desk',
      labelKey: 'review.finance.desk',
      cellDataType: 'text',
      minWidth: 145,
      sortable: true,
      filter: 'agTextColumnFilter',
      filterParams: { filterOptions: ['equals', 'notEqual'] },
      editable: true,
      cellEditor: 'agSelectCellEditor',
      cellEditorParams: { values: ['Credit', 'Rates', 'Treasury', 'Structured'] },
      validationRules: [{ key: 'required', message: 'Desk is required.' }],
    },
    {
      colId: 'reviewStatus',
      field: 'reviewStatus',
      labelKey: 'review.finance.reviewStatus',
      cellDataType: 'text',
      minWidth: 155,
      sortable: true,
      filter: 'agTextColumnFilter',
      filterParams: { filterOptions: ['equals', 'notEqual'] },
      editable: true,
      cellEditor: 'agSelectCellEditor',
      cellEditorParams: { values: ['Open', 'Submitted', 'Approved', 'Escalated'] },
      cellRenderer: 'reviewStatus',
      validationRules: [
        { key: 'required', message: 'Review status is required.' },
        {
          key: 'financeReviewStatus',
          message: 'Review status must be Open, Submitted, Approved, or Escalated.',
        },
      ],
    },
    {
      colId: 'utilizationPct',
      field: 'utilizationPct',
      labelKey: 'review.finance.utilizationPct',
      cellDataType: 'number',
      type: 'numericColumn',
      minWidth: 150,
      sortable: true,
      filter: 'agNumberColumnFilter',
      filterParams: {
        filterOptions: [
          'equals',
          'notEqual',
          'greaterThan',
          'greaterThanOrEqual',
          'lessThan',
          'lessThanOrEqual',
        ],
      },
      editable: true,
      cellEditor: 'agNumberCellEditor',
      cellEditorParams: { min: 0, max: 100 },
      valueFormatterKey: 'percentage',
      validationRules: [
        {
          key: 'numberRange',
          params: { min: 0, max: 100 },
          message: 'Utilization must be between 0 and 100.',
        },
      ],
    },
    {
      colId: 'nextReviewDate',
      field: 'nextReviewDate',
      labelKey: 'review.finance.nextReviewDate',
      cellDataType: 'dateString',
      minWidth: 175,
      sortable: true,
      filter: 'agDateColumnFilter',
      filterParams: {
        filterOptions: ['equals', 'notEqual', 'lessThan', 'greaterThan'],
      },
      editable: true,
      cellEditor: 'agTextCellEditor',
      valueFormatterKey: 'dateText',
      validationRules: [
        { key: 'required', message: 'Next review date is required.' },
        { key: 'isoDate', message: 'Next review date must use YYYY-MM-DD.' },
      ],
    },
  ],
};
